export const BASE_URL = 'http://localhost:5000'
export const USERS_URL = '/api/users'
export const ORDER_URL = '/api/order'
export const CONTRACT_URL = '/api/contract'
export const CHAT_URL = '/api/chat'
export const FRONT_URL = 'http://localhost:5173'
